using DPDP.Application.Common.Interfaces;
using Microsoft.Extensions.Options;

namespace DPDP.Infrastructure.Storage;

/// <summary>
/// The only IObjectStorageService implementation today — stores objects
/// under a local directory rather than a real S3/MinIO bucket. Keys are
/// always server-generated by the caller (see EvidenceItem/EvidenceVersion
/// in Domain), but this class still independently rejects any key
/// attempting to escape the root (".." segments, absolute paths) as
/// defense in depth — never trust "the caller already validated it" alone
/// for path construction. Swapping to a real S3-compatible client (MinIO,
/// AWS S3, Azure Blob via its S3-compatible gateway) is a new
/// implementation of this same interface plus a DI registration change;
/// no command handler changes. See docs/ARCHITECTURE.md Module 7 section.
/// </summary>
public sealed class FileSystemObjectStorageService : IObjectStorageService
{
    private readonly string _rootPath;

    public FileSystemObjectStorageService(IOptions<ObjectStorageOptions> options)
    {
        _rootPath = Path.GetFullPath(options.Value.RootPath);
        Directory.CreateDirectory(_rootPath);
    }

    public async Task UploadAsync(string key, Stream content, string contentType, CancellationToken cancellationToken = default)
    {
        var path = ResolveSafePath(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        await using var fileStream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None);
        await content.CopyToAsync(fileStream, cancellationToken);
    }

    public async Task<Stream> DownloadAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = ResolveSafePath(key);
        if (!File.Exists(path))
        {
            throw new FileNotFoundException("The requested object does not exist in storage.", key);
        }

        var memoryStream = new MemoryStream();
        await using (var fileStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read))
        {
            await fileStream.CopyToAsync(memoryStream, cancellationToken);
        }

        memoryStream.Position = 0;
        return memoryStream;
    }

    public Task DeleteAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = ResolveSafePath(key);
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    private string ResolveSafePath(string key)
    {
        if (string.IsNullOrWhiteSpace(key) || key.Contains("..") || Path.IsPathRooted(key))
        {
            throw new ArgumentException("Object storage key is invalid.", nameof(key));
        }

        var fullPath = Path.GetFullPath(Path.Combine(_rootPath, key));
        if (!fullPath.StartsWith(_rootPath, StringComparison.Ordinal))
        {
            throw new ArgumentException("Object storage key resolves outside the storage root.", nameof(key));
        }

        return fullPath;
    }
}
