namespace DPDP.Application.Modules.Evidence.DTOs;

public sealed record EvidenceSummaryDto(
    Guid Id,
    string EvidenceNumber,
    string Title,
    string EvidenceType,
    string Status,
    Guid? OwnerUserId,
    string? OwnerName,
    Guid? ReviewerUserId,
    string? ReviewerName,
    DateOnly? ExpiryDate,
    bool IsExpired,
    int CurrentVersionNumber,
    DateTimeOffset CreatedAt);

public sealed record EvidenceDetailDto(
    Guid Id,
    string EvidenceNumber,
    string Title,
    string? Description,
    string EvidenceType,
    string Status,
    Guid? AssessmentId,
    Guid? ControlId,
    string? ControlBusinessId,
    string? ControlName,
    Guid? FindingId,
    string? FindingNumber,
    string? VendorReference,
    string? ProcessingActivityReference,
    Guid? OwnerUserId,
    string? OwnerName,
    Guid? ReviewerUserId,
    string? ReviewerName,
    DateOnly? ExpiryDate,
    bool IsExpired,
    DateTimeOffset? ApprovedAt,
    DateTimeOffset? RejectedAt,
    string? RejectionReason,
    DateTimeOffset? ArchivedAt,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    IReadOnlyList<EvidenceVersionDto> Versions,
    IReadOnlyList<EvidenceReviewRecordDto> Reviews);
