// <auto-generated />
using System;
using DPDP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DPDP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DpdpDbContext))]
    [Migration("20260907104222_IdentityAndRbac")]
    partial class IdentityAndRbac
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DPDP.Domain.Modules.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("action");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.HasIndex("OrganisationId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_organisation_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttemptedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("attempted_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_history_user_id");

                    b.HasIndex("OrganisationId", "CreatedAt")
                        .HasDatabaseName("ix_login_history_organisation_id_created_at");

                    b.ToTable("login_history", (string)null);
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_key");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View organisation details.",
                            Key = "organisation.read",
                            Module = "Organisations"
                        },
                        new
                        {
                            Id = new Guid("9a82dbe9-a3ad-f54c-6b31-862958cd736e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Edit organisation details.",
                            Key = "organisation.write",
                            Module = "Organisations"
                        },
                        new
                        {
                            Id = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View users.",
                            Key = "users.read",
                            Module = "Identity"
                        },
                        new
                        {
                            Id = new Guid("270b3031-1aa9-3b41-9a31-af214c8a2ce8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create users.",
                            Key = "users.create",
                            Module = "Identity"
                        },
                        new
                        {
                            Id = new Guid("52e1133d-e4e1-d3f4-af93-6ec8397d590f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Edit user profile details.",
                            Key = "users.update",
                            Module = "Identity"
                        },
                        new
                        {
                            Id = new Guid("1aee2fe5-144e-d283-2f85-761b8641974e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Activate or deactivate user accounts.",
                            Key = "users.disable",
                            Module = "Identity"
                        },
                        new
                        {
                            Id = new Guid("5cae153a-0854-ee73-1a78-b7053d97b7b3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View roles and their permissions.",
                            Key = "roles.read",
                            Module = "Identity"
                        },
                        new
                        {
                            Id = new Guid("e9d6c2e4-4c7a-9623-4c5d-ea01f69902da"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Assign roles to users.",
                            Key = "roles.manage",
                            Module = "Identity"
                        },
                        new
                        {
                            Id = new Guid("ee6179a3-5935-9799-56b8-84d64c94b72f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View compliance assessments.",
                            Key = "assessments.read",
                            Module = "Assessments"
                        },
                        new
                        {
                            Id = new Guid("bf83dd9d-0066-7e7b-ebcd-97d308590c37"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create compliance assessments.",
                            Key = "assessments.create",
                            Module = "Assessments"
                        },
                        new
                        {
                            Id = new Guid("fbdadc99-1531-a501-16d0-21e226fa2805"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Approve compliance assessments.",
                            Key = "assessments.approve",
                            Module = "Assessments"
                        },
                        new
                        {
                            Id = new Guid("a8027187-eae2-da2c-06f5-b78ea7161fc2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View the DPDP control library.",
                            Key = "controls.read",
                            Module = "Controls"
                        },
                        new
                        {
                            Id = new Guid("1dd266e6-943a-c8e6-439e-c591fadbfe47"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Manage the DPDP control library.",
                            Key = "controls.manage",
                            Module = "Controls"
                        },
                        new
                        {
                            Id = new Guid("67227c72-d6b2-f692-36f8-77d2928cc300"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View the risk register.",
                            Key = "risks.read",
                            Module = "Risk"
                        },
                        new
                        {
                            Id = new Guid("56f53b5e-cc9d-a5ab-a530-156b8e41338b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Manage the risk register.",
                            Key = "risks.manage",
                            Module = "Risk"
                        },
                        new
                        {
                            Id = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View findings.",
                            Key = "findings.read",
                            Module = "Findings"
                        },
                        new
                        {
                            Id = new Guid("6caa7dbb-db5e-7f31-7c2a-82eecc185418"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create findings.",
                            Key = "findings.create",
                            Module = "Findings"
                        },
                        new
                        {
                            Id = new Guid("988207d4-1001-ac73-1c9e-4ad2aee51034"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Assign findings.",
                            Key = "findings.assign",
                            Module = "Findings"
                        },
                        new
                        {
                            Id = new Guid("f73a3e44-9927-3d6a-4988-aa89192bc7a4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Close findings.",
                            Key = "findings.close",
                            Module = "Findings"
                        },
                        new
                        {
                            Id = new Guid("b34c0975-ac31-2467-c654-0138fd16d87c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View remediation tasks.",
                            Key = "remediation.read",
                            Module = "Remediation"
                        },
                        new
                        {
                            Id = new Guid("5e1669e0-3f9e-22eb-841f-68cac453d67e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Manage remediation tasks.",
                            Key = "remediation.manage",
                            Module = "Remediation"
                        },
                        new
                        {
                            Id = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View evidence.",
                            Key = "evidence.read",
                            Module = "Evidence"
                        },
                        new
                        {
                            Id = new Guid("5b1cabb3-30a0-dc0c-bc2d-c160cf86c6ee"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Upload evidence.",
                            Key = "evidence.upload",
                            Module = "Evidence"
                        },
                        new
                        {
                            Id = new Guid("c4c4da74-fa5e-e2e6-cf26-1e2480932e79"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Review and approve evidence.",
                            Key = "evidence.review",
                            Module = "Evidence"
                        },
                        new
                        {
                            Id = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View reports.",
                            Key = "reports.read",
                            Module = "Reports"
                        },
                        new
                        {
                            Id = new Guid("025496a9-f552-36a2-4439-70e5d7732dd8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Generate reports.",
                            Key = "reports.generate",
                            Module = "Reports"
                        },
                        new
                        {
                            Id = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View the audit trail.",
                            Key = "audit.read",
                            Module = "Audit"
                        });
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Full, cross-tenant administrative access to the entire platform.",
                            IsSystemRole = true,
                            Name = "Super Administrator"
                        },
                        new
                        {
                            Id = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Full administrative access within one organisation.",
                            IsSystemRole = true,
                            Name = "Organisation Administrator"
                        },
                        new
                        {
                            Id = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Manages privacy compliance activities: assessments, findings, evidence.",
                            IsSystemRole = true,
                            Name = "Privacy Officer"
                        },
                        new
                        {
                            Id = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Oversees compliance posture: approves assessments, closes findings.",
                            IsSystemRole = true,
                            Name = "Compliance Officer"
                        },
                        new
                        {
                            Id = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Manages security controls, risk, and incident-adjacent findings.",
                            IsSystemRole = true,
                            Name = "Security Officer"
                        },
                        new
                        {
                            Id = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Manages user accounts and technical controls.",
                            IsSystemRole = true,
                            Name = "IT Administrator"
                        },
                        new
                        {
                            Id = new Guid("0c0ea005-06ac-bbdc-08b1-7f0ab269cf9b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Departmental visibility into assessments, findings, and evidence.",
                            IsSystemRole = true,
                            Name = "Department Owner"
                        },
                        new
                        {
                            Id = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read-only access across the platform, plus the audit trail.",
                            IsSystemRole = true,
                            Name = "Auditor"
                        },
                        new
                        {
                            Id = new Guid("5ae77166-b24b-7aa3-eccb-ad8a4106b434"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Executive read-only visibility into compliance posture and reports.",
                            IsSystemRole = true,
                            Name = "Management"
                        },
                        new
                        {
                            Id = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Minimal read-only access.",
                            IsSystemRole = true,
                            Name = "Read Only"
                        });
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("9a82dbe9-a3ad-f54c-6b31-862958cd736e")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("270b3031-1aa9-3b41-9a31-af214c8a2ce8")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("52e1133d-e4e1-d3f4-af93-6ec8397d590f")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("1aee2fe5-144e-d283-2f85-761b8641974e")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("5cae153a-0854-ee73-1a78-b7053d97b7b3")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("e9d6c2e4-4c7a-9623-4c5d-ea01f69902da")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("ee6179a3-5935-9799-56b8-84d64c94b72f")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("bf83dd9d-0066-7e7b-ebcd-97d308590c37")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("fbdadc99-1531-a501-16d0-21e226fa2805")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("a8027187-eae2-da2c-06f5-b78ea7161fc2")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("1dd266e6-943a-c8e6-439e-c591fadbfe47")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("67227c72-d6b2-f692-36f8-77d2928cc300")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("56f53b5e-cc9d-a5ab-a530-156b8e41338b")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("6caa7dbb-db5e-7f31-7c2a-82eecc185418")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("988207d4-1001-ac73-1c9e-4ad2aee51034")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("f73a3e44-9927-3d6a-4988-aa89192bc7a4")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("b34c0975-ac31-2467-c654-0138fd16d87c")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("5e1669e0-3f9e-22eb-841f-68cac453d67e")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("5b1cabb3-30a0-dc0c-bc2d-c160cf86c6ee")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("c4c4da74-fa5e-e2e6-cf26-1e2480932e79")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("025496a9-f552-36a2-4439-70e5d7732dd8")
                        },
                        new
                        {
                            RoleId = new Guid("016c7d6f-109e-eed9-173a-a65559a34eca"),
                            PermissionId = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("9a82dbe9-a3ad-f54c-6b31-862958cd736e")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("270b3031-1aa9-3b41-9a31-af214c8a2ce8")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("52e1133d-e4e1-d3f4-af93-6ec8397d590f")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("1aee2fe5-144e-d283-2f85-761b8641974e")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("5cae153a-0854-ee73-1a78-b7053d97b7b3")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("e9d6c2e4-4c7a-9623-4c5d-ea01f69902da")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("ee6179a3-5935-9799-56b8-84d64c94b72f")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("a8027187-eae2-da2c-06f5-b78ea7161fc2")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("67227c72-d6b2-f692-36f8-77d2928cc300")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("b34c0975-ac31-2467-c654-0138fd16d87c")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("025496a9-f552-36a2-4439-70e5d7732dd8")
                        },
                        new
                        {
                            RoleId = new Guid("826bf6be-b10e-9fa5-f81e-2c42fa12eb7f"),
                            PermissionId = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("5cae153a-0854-ee73-1a78-b7053d97b7b3")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("ee6179a3-5935-9799-56b8-84d64c94b72f")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("bf83dd9d-0066-7e7b-ebcd-97d308590c37")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("a8027187-eae2-da2c-06f5-b78ea7161fc2")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("67227c72-d6b2-f692-36f8-77d2928cc300")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("6caa7dbb-db5e-7f31-7c2a-82eecc185418")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("b34c0975-ac31-2467-c654-0138fd16d87c")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("5b1cabb3-30a0-dc0c-bc2d-c160cf86c6ee")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("025496a9-f552-36a2-4439-70e5d7732dd8")
                        },
                        new
                        {
                            RoleId = new Guid("087fab86-e2f5-4349-5f7b-48ee28bc751f"),
                            PermissionId = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("5cae153a-0854-ee73-1a78-b7053d97b7b3")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("ee6179a3-5935-9799-56b8-84d64c94b72f")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("bf83dd9d-0066-7e7b-ebcd-97d308590c37")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("fbdadc99-1531-a501-16d0-21e226fa2805")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("a8027187-eae2-da2c-06f5-b78ea7161fc2")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("1dd266e6-943a-c8e6-439e-c591fadbfe47")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("67227c72-d6b2-f692-36f8-77d2928cc300")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("988207d4-1001-ac73-1c9e-4ad2aee51034")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("f73a3e44-9927-3d6a-4988-aa89192bc7a4")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("b34c0975-ac31-2467-c654-0138fd16d87c")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("5e1669e0-3f9e-22eb-841f-68cac453d67e")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("c4c4da74-fa5e-e2e6-cf26-1e2480932e79")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("025496a9-f552-36a2-4439-70e5d7732dd8")
                        },
                        new
                        {
                            RoleId = new Guid("2ee608de-7ae0-64a2-ed3b-8da1f985c363"),
                            PermissionId = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("5cae153a-0854-ee73-1a78-b7053d97b7b3")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("a8027187-eae2-da2c-06f5-b78ea7161fc2")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("1dd266e6-943a-c8e6-439e-c591fadbfe47")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("67227c72-d6b2-f692-36f8-77d2928cc300")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("56f53b5e-cc9d-a5ab-a530-156b8e41338b")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("988207d4-1001-ac73-1c9e-4ad2aee51034")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("f73a3e44-9927-3d6a-4988-aa89192bc7a4")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("b34c0975-ac31-2467-c654-0138fd16d87c")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("5e1669e0-3f9e-22eb-841f-68cac453d67e")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("c4c4da74-fa5e-e2e6-cf26-1e2480932e79")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f")
                        },
                        new
                        {
                            RoleId = new Guid("69fa55a0-5741-9bc0-4e51-c0834d45bc66"),
                            PermissionId = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("270b3031-1aa9-3b41-9a31-af214c8a2ce8")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("52e1133d-e4e1-d3f4-af93-6ec8397d590f")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("1aee2fe5-144e-d283-2f85-761b8641974e")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("5cae153a-0854-ee73-1a78-b7053d97b7b3")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("a8027187-eae2-da2c-06f5-b78ea7161fc2")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("5b1cabb3-30a0-dc0c-bc2d-c160cf86c6ee")
                        },
                        new
                        {
                            RoleId = new Guid("b98e94e4-9a76-5548-996c-e66e1750e203"),
                            PermissionId = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7")
                        },
                        new
                        {
                            RoleId = new Guid("0c0ea005-06ac-bbdc-08b1-7f0ab269cf9b"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("0c0ea005-06ac-bbdc-08b1-7f0ab269cf9b"),
                            PermissionId = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d")
                        },
                        new
                        {
                            RoleId = new Guid("0c0ea005-06ac-bbdc-08b1-7f0ab269cf9b"),
                            PermissionId = new Guid("ee6179a3-5935-9799-56b8-84d64c94b72f")
                        },
                        new
                        {
                            RoleId = new Guid("0c0ea005-06ac-bbdc-08b1-7f0ab269cf9b"),
                            PermissionId = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4")
                        },
                        new
                        {
                            RoleId = new Guid("0c0ea005-06ac-bbdc-08b1-7f0ab269cf9b"),
                            PermissionId = new Guid("b34c0975-ac31-2467-c654-0138fd16d87c")
                        },
                        new
                        {
                            RoleId = new Guid("0c0ea005-06ac-bbdc-08b1-7f0ab269cf9b"),
                            PermissionId = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb")
                        },
                        new
                        {
                            RoleId = new Guid("0c0ea005-06ac-bbdc-08b1-7f0ab269cf9b"),
                            PermissionId = new Guid("5b1cabb3-30a0-dc0c-bc2d-c160cf86c6ee")
                        },
                        new
                        {
                            RoleId = new Guid("0c0ea005-06ac-bbdc-08b1-7f0ab269cf9b"),
                            PermissionId = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("5cae153a-0854-ee73-1a78-b7053d97b7b3")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("ee6179a3-5935-9799-56b8-84d64c94b72f")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("a8027187-eae2-da2c-06f5-b78ea7161fc2")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("67227c72-d6b2-f692-36f8-77d2928cc300")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("b34c0975-ac31-2467-c654-0138fd16d87c")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f")
                        },
                        new
                        {
                            RoleId = new Guid("3425d982-2f29-47ea-46bd-c2ad128e542a"),
                            PermissionId = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7")
                        },
                        new
                        {
                            RoleId = new Guid("5ae77166-b24b-7aa3-eccb-ad8a4106b434"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("5ae77166-b24b-7aa3-eccb-ad8a4106b434"),
                            PermissionId = new Guid("ee6179a3-5935-9799-56b8-84d64c94b72f")
                        },
                        new
                        {
                            RoleId = new Guid("5ae77166-b24b-7aa3-eccb-ad8a4106b434"),
                            PermissionId = new Guid("67227c72-d6b2-f692-36f8-77d2928cc300")
                        },
                        new
                        {
                            RoleId = new Guid("5ae77166-b24b-7aa3-eccb-ad8a4106b434"),
                            PermissionId = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4")
                        },
                        new
                        {
                            RoleId = new Guid("5ae77166-b24b-7aa3-eccb-ad8a4106b434"),
                            PermissionId = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f")
                        },
                        new
                        {
                            RoleId = new Guid("5ae77166-b24b-7aa3-eccb-ad8a4106b434"),
                            PermissionId = new Guid("025496a9-f552-36a2-4439-70e5d7732dd8")
                        },
                        new
                        {
                            RoleId = new Guid("5ae77166-b24b-7aa3-eccb-ad8a4106b434"),
                            PermissionId = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("a5acab85-c910-8b1c-d3b0-b2b8ccbcd1fb")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("cc9f6165-e27e-7892-b1ac-ea069cfa364d")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("5cae153a-0854-ee73-1a78-b7053d97b7b3")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("ee6179a3-5935-9799-56b8-84d64c94b72f")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("a8027187-eae2-da2c-06f5-b78ea7161fc2")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("67227c72-d6b2-f692-36f8-77d2928cc300")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("533af64f-df74-7a52-8af7-e511db0e93d4")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("b34c0975-ac31-2467-c654-0138fd16d87c")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("8f668761-f357-5e37-cc7f-65980d2c4adb")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("f1aed973-70b5-2e78-4153-0f4a6f1be34f")
                        },
                        new
                        {
                            RoleId = new Guid("d3006dac-83c9-c7fb-25eb-66f36565a3cc"),
                            PermissionId = new Guid("cdaa5381-1bf1-cdce-f39c-8e77089e77b7")
                        });
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mfa_secret");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_stamp");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email")
                        .HasFilter("organisation_id IS NULL");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_users_organisation_id");

                    b.HasIndex("OrganisationId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_organisation_id_normalized_email")
                        .HasFilter("organisation_id IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_role_id")
                        .HasFilter("organisation_id IS NULL");

                    b.HasIndex("UserId", "RoleId", "OrganisationId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_role_id_organisation_id")
                        .HasFilter("organisation_id IS NOT NULL");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LegalName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("DPDP.Domain.Modules.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.RefreshToken", b =>
                {
                    b.HasOne("DPDP.Domain.Modules.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.RolePermission", b =>
                {
                    b.HasOne("DPDP.Domain.Modules.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("DPDP.Domain.Modules.Identity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.User", b =>
                {
                    b.HasOne("DPDP.Domain.Modules.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_organisations_organisation_id");
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.UserRole", b =>
                {
                    b.HasOne("DPDP.Domain.Modules.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("DPDP.Domain.Modules.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DPDP.Domain.Modules.Identity.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
